# Generated by Django 3.2.12 on 2022-03-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_removed',
        ),
    ]
