# Generated by Django 3.2.12 on 2022-03-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220303_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
